apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k3s-experiments
deploy:
  kubectl:
    manifests:
    - services/hello/k8s/local/service.yaml
    - services/hello/k8s/local/daemon-set.yaml
    - services/hello/k8s/local/daemon-set.arm.yaml
    - services/echo-rust/k8s/local/service.yaml
    - k8s/local/roscore-daemon-set.arm.yaml
build:
  insecureRegistries: 
    - registry.local:5000

  local:
    push: true

  artifacts:
  - image: hello
    bazel:
      target: //services/hello:hello.tar
      args:
        - "--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64"
    # Need to define another build artifact to compile for ARM
    # There is still no support in Bazel for multiarch docker images
    # https://github.com/bazelbuild/rules_docker/issues/300
  - image: hello_arm
    bazel:
      target: //services/hello:hello.tar
      args:
        - "--platforms=@io_bazel_rules_go//go/toolchain:linux_arm"

  - image: echo-rust
    bazel:
      target: //services/echo-rust:echo-rust.tar
      # args:
      #   - "--platforms=@rules_rust//rust/platform:arm-unknown-linux-gnueabi"
