apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-rust-local-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1  # TODO: what does this do?
spec:
  rules:
    - host: echo-rust.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: echo-rust-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-rust
spec:
  selector:
    matchLabels:
      app: echo-rust
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-rust
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: echo-rust
          image: echo-rust # rule name in bazel
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
            requests:
              cpu: 100m
              memory: 10Mi
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echo-rust-service
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: echo-rust
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: echo-rust-headless
  labels:
    env: dev
spec:
  clusterIP: None
  # type: NodePort
  selector:
    app: echo-rust
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

